"""Generates the two Kaggle notebooks.  Run this, don't hand-edit the .ipynb."""
import json, pathlib

def md(*lines):  return {"cell_type":"markdown","metadata":{},"source":list(lines)}
def code(*lines): return {"cell_type":"code","execution_count":None,"metadata":{},
                          "outputs":[],"source":list(lines)}
def nb(cells, name):
    doc = {"cells":cells,
           "metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},
                       "language_info":{"name":"python","version":"3.11"},
                       "accelerator":"GPU"},
           "nbformat":4,"nbformat_minor":5}
    pathlib.Path(name).write_text(json.dumps(doc, indent=1))
    print("wrote", name, f"({len(cells)} cells)")

# ===========================================================================
# NOTEBOOK 1 -- online prefetch (T4, internet ON)
# ===========================================================================
c1 = [
md("# 01 - Prefetch assets (ONLINE)\n",
   "\n",
   "Run this **once**, on any accelerator, with **Internet ON**.\n",
   "It vendors everything the offline run needs into `/kaggle/working`, which you then\n",
   "attach to notebook 02 as a dataset.\n",
   "\n",
   "| Asset | Size | Why it is needed |\n",
   "|---|---|---|\n",
   "| This project's repo | small | the `mlrx` package |\n",
   "| NVlabs/edm | small | the pretrained `.pkl` cannot be unpickled without `torch_utils`, `dnnlib`, `training.networks` |\n",
   "| EDM CIFAR-10 cond checkpoint | 213 MB | the denoiser |\n",
   "| Inception-v3 (StyleGAN3 port) | 91 MB | FID features; torchvision's Inception gives different numbers |\n",
   "| CIFAR-10 FID reference stats | 32 MB | the reference mu/sigma |\n",
   "| pip wheels | small | anything missing from the offline image |\n",
   "\n",
   "Total roughly **340 MB**.\n"),

code("REPO_URL = 'https://github.com/azraihan/multi-level-richardson-faster-diffusion-ode'\n",
     "REPO_BRANCH = 'main'          # or a tag/commit for a reproducible pin\n",
     "EDM_COMMIT  = 'main'          # NVlabs/edm\n",
     "\n",
     "OUT = '/kaggle/working'\n",
     "\n",
     "ASSETS = {\n",
     "    'edm-cifar10-32x32-cond-vp.pkl':\n",
     "        'https://nvlabs-fi-cdn.nvidia.com/edm/pretrained/edm-cifar10-32x32-cond-vp.pkl',\n",
     "    'cifar10-32x32.npz':\n",
     "        'https://nvlabs-fi-cdn.nvidia.com/edm/fid-refs/cifar10-32x32.npz',\n",
     "    'inception-2015-12-05.pkl':\n",
     "        'https://api.ngc.nvidia.com/v2/models/nvidia/research/stylegan3/versions/1/'\n",
     "        'files/metrics/inception-2015-12-05.pkl',\n",
     "}\n",
     "\n",
     "# Present in Kaggle's image already, but pinned here so the offline notebook\n",
     "# never has to reach the network even if the base image changes.\n",
     "WHEELS = ['click', 'tqdm', 'requests', 'psutil', 'imageio', 'pyspng']\n"),

code("import os, subprocess, sys, time, json, hashlib, urllib.request\n",
     "\n",
     "def sh(cmd, **kw):\n",
     "    print('$', cmd, flush=True)\n",
     "    r = subprocess.run(cmd, shell=True, text=True, capture_output=True, **kw)\n",
     "    if r.stdout.strip(): print(r.stdout.strip()[:2000])\n",
     "    if r.returncode != 0:\n",
     "        print(r.stderr.strip()[:4000]); raise RuntimeError(f'failed: {cmd}')\n",
     "    return r\n",
     "\n",
     "for d in ('repo', 'third_party', 'assets', 'wheels'):\n",
     "    os.makedirs(f'{OUT}/{d}', exist_ok=True)\n",
     "print('workspace ready')\n"),

md("## Clone the sources"),
code("sh(f'git clone --depth 1 --branch {REPO_BRANCH} {REPO_URL} {OUT}/repo/project')\n",
     "sh(f'git clone --depth 1 https://github.com/NVlabs/edm.git {OUT}/third_party/edm')\n",
     "\n",
     "# The pickle needs these three importable; fail loudly now rather than\n",
     "# halfway through the offline run.\n",
     "for m in ('torch_utils', 'dnnlib', 'training'):\n",
     "    assert os.path.isdir(f'{OUT}/third_party/edm/{m}'), f'missing {m} in NVlabs/edm'\n",
     "print('\\nboth repos present, edm has torch_utils / dnnlib / training')\n"),

md("## Download the model, the FID detector, and the reference statistics"),
code("def fetch(url, dest, retries=3):\n",
     "    if os.path.exists(dest) and os.path.getsize(dest) > 0:\n",
     "        print(f'  cached  {os.path.basename(dest)} '\n",
     "              f'({os.path.getsize(dest)/2**20:.1f} MB)'); return dest\n",
     "    for k in range(retries):\n",
     "        try:\n",
     "            t0 = time.time()\n",
     "            with urllib.request.urlopen(url, timeout=120) as r, open(dest, 'wb') as f:\n",
     "                total = int(r.headers.get('content-length', 0)); done = 0\n",
     "                while True:\n",
     "                    chunk = r.read(1 << 20)\n",
     "                    if not chunk: break\n",
     "                    f.write(chunk); done += len(chunk)\n",
     "                    if total:\n",
     "                        print(f'\\r  {os.path.basename(dest)}  '\n",
     "                              f'{done/2**20:7.1f}/{total/2**20:.1f} MB', end='')\n",
     "            print(f'\\r  {os.path.basename(dest)}  {done/2**20:7.1f} MB  '\n",
     "                  f'in {time.time()-t0:.0f}s')\n",
     "            return dest\n",
     "        except Exception as e:\n",
     "            print(f'\\n  attempt {k+1} failed: {e!r}')\n",
     "            if os.path.exists(dest): os.remove(dest)\n",
     "            if k == retries - 1: raise\n",
     "            time.sleep(5)\n",
     "\n",
     "for name, url in ASSETS.items():\n",
     "    fetch(url, f'{OUT}/assets/{name}')\n"),

md("## Vendor pip wheels\n",
   "\n",
   "So the offline notebook can `pip install --no-index` if the base image is missing anything."),
code("sh(f'pip download -q -d {OUT}/wheels --no-deps ' + ' '.join(WHEELS) + ' || true')\n",
     "ws = os.listdir(f'{OUT}/wheels')\n",
     "print(f'{len(ws)} wheels vendored')\n",
     "for w in sorted(ws)[:20]: print('  ', w)\n"),

md("## Verify and write the manifest\n",
   "\n",
   "The manifest is the sentinel notebook 02 looks for when it auto-discovers the mount."),
code("import torch\n",
     "\n",
     "man = {'created': time.strftime('%Y-%m-%d %H:%M:%S'),\n",
     "       'repo_url': REPO_URL, 'repo_branch': REPO_BRANCH, 'assets': {}}\n",
     "\n",
     "ok = True\n",
     "for name in ASSETS:\n",
     "    p = f'{OUT}/assets/{name}'\n",
     "    n = os.path.getsize(p)\n",
     "    h = hashlib.sha256(open(p,'rb').read()).hexdigest()[:16]\n",
     "    man['assets'][name] = {'bytes': n, 'sha256_16': h}\n",
     "    print(f'  {name:<40} {n/2**20:8.1f} MB  sha256:{h}')\n",
     "    if n < 1 << 20: ok = False; print('     ^ suspiciously small')\n",
     "\n",
     "# Prove the checkpoint actually loads with this edm checkout.\n",
     "sys.path.insert(0, f'{OUT}/third_party/edm')\n",
     "import pickle\n",
     "with open(f'{OUT}/assets/edm-cifar10-32x32-cond-vp.pkl','rb') as f:\n",
     "    net = pickle.load(f)['ema']\n",
     "print(f\"\\ncheckpoint loads: {type(net).__name__}, \"\n",
     "      f\"{net.img_resolution}x{net.img_resolution}, label_dim={net.label_dim}, \"\n",
     "      f\"sigma in [{net.sigma_min}, {net.sigma_max}]\")\n",
     "man['network'] = {'class': type(net).__name__,\n",
     "                  'img_resolution': int(net.img_resolution),\n",
     "                  'label_dim': int(net.label_dim)}\n",
     "\n",
     "json.dump(man, open(f'{OUT}/manifest.json','w'), indent=2)\n",
     "print('\\nmanifest.json written.' if ok else '\\nPROBLEM: re-run before using offline.')\n"),

md("## Done\n",
   "\n",
   "**Save Version -> Save & Run All.** Then in notebook 02, add this notebook's\n",
   "output via **+ Add Input -> Your Work -> Notebooks**, and set `PREFETCH_NAME`\n",
   "there to this notebook's slug.\n"),
code("sh(f'du -sh {OUT}/* | sort -h')\n"),
]
nb(c1, "01_prefetch_online.ipynb")

# ===========================================================================
# NOTEBOOK 2 -- offline pipeline (RTX 6000, internet OFF)
# ===========================================================================
c2 = [
md("# 02 - Multi-level Richardson extrapolation: full pipeline (OFFLINE)\n",
   "\n",
   "Runs end to end with **no network access**. Attach the output of `01_prefetch_online`\n",
   "as an input dataset first.\n",
   "\n",
   "Produces, under `/kaggle/working/outputs`:\n",
   "* `results/*.csv` - every number, one table per study\n",
   "* `figures/*.pdf` - one caption-less vector figure per result\n",
   "* `figures/data/*.csv` - the exact numbers behind each figure, for restyling later\n",
   "\n",
   "**The GPU stage is resumable.** Re-running skips configurations already in\n",
   "`results/fid_results.csv`, so if the session dies, just run it again.\n"),

code("# ---- the one thing you may need to change -------------------------------\n",
     "PREFETCH_NAME = None   # e.g. '01-prefetch-online'; None = auto-discover\n",
     "\n",
     "# ---- experiment budget --------------------------------------------------\n",
     "N_IMAGES  = 10_000               # per FID (paper uses 50k; see note below)\n",
     "NFE_GRID  = (6, 8, 10, 12, 16, 20)\n",
     "BATCH     = 256                  # raise on a 24 GB card\n",
     "QUICK_CPU = False\n",
     "RUN_GPU   = True\n",
     "INCLUDE_REUSE   = True           # reuse-vs-exact arm\n",
     "DO_RHO_SEARCH   = True\n",
     "\n",
     "OUTDIR = '/kaggle/working/outputs'\n"),

md("## Locate the prefetched input\n",
   "\n",
   "Searches the documented path first, then falls back to scanning `/kaggle/input`\n",
   "for the `manifest.json` sentinel, so a differing mount layout is not fatal."),
code("import os, sys, glob, json, time, subprocess\n",
     "\n",
     "def find_prefetch():\n",
     "    cands = []\n",
     "    if PREFETCH_NAME:\n",
     "        cands += [f'/kaggle/input/notebooks/raihanzahin/{PREFETCH_NAME}',\n",
     "                  f'/kaggle/input/{PREFETCH_NAME}']\n",
     "    cands += sorted(glob.glob('/kaggle/input/notebooks/*/*'))\n",
     "    cands += sorted(glob.glob('/kaggle/input/*'))\n",
     "    cands += ['/kaggle/working']\n",
     "    for c in cands:\n",
     "        if os.path.exists(os.path.join(c, 'manifest.json')):\n",
     "            return c\n",
     "    raise SystemExit(\n",
     "        'Could not find the prefetch output (no manifest.json).\\n'\n",
     "        'Add notebook 01 output via + Add Input, then set PREFETCH_NAME.\\n'\n",
     "        'Searched:\\n  ' + '\\n  '.join(cands[:25]))\n",
     "\n",
     "IN = find_prefetch()\n",
     "man = json.load(open(f'{IN}/manifest.json'))\n",
     "print('prefetch:', IN)\n",
     "print('created :', man['created'])\n",
     "for k, v in man['assets'].items():\n",
     "    print(f\"  {k:<40} {v['bytes']/2**20:8.1f} MB\")\n",
     "\n",
     "REPO = f'{IN}/repo/project'\n",
     "EDM  = f'{IN}/third_party/edm'\n",
     "ASSETS = f'{IN}/assets'\n",
     "for p in (REPO, EDM, ASSETS):\n",
     "    assert os.path.isdir(p), p\n"),

code("# Offline wheel install (no-op if the image already has everything).\n",
     "w = f'{IN}/wheels'\n",
     "if os.path.isdir(w) and os.listdir(w):\n",
     "    subprocess.run(f'pip install -q --no-index --find-links {w} '\n",
     "                   f'click tqdm requests psutil', shell=True)\n",
     "\n",
     "sys.path.insert(0, f'{REPO}/src')\n",
     "sys.path.insert(0, EDM)\n",
     "os.environ['EDM_ROOT'] = EDM\n",
     "\n",
     "import torch, numpy as np, matplotlib\n",
     "matplotlib.use('Agg')\n",
     "import mlrx\n",
     "print('mlrx', mlrx.__version__)\n",
     "print('torch', torch.__version__, '| cuda', torch.cuda.is_available(),\n",
     "      '| devices', torch.cuda.device_count())\n",
     "if torch.cuda.is_available():\n",
     "    for i in range(torch.cuda.device_count()):\n",
     "        p = torch.cuda.get_device_properties(i)\n",
     "        print(f'  [{i}] {p.name}  {p.total_memory/2**30:.1f} GB')\n"),

md("## Correctness gate\n",
   "\n",
   "The test suite includes a bit-exact comparison against the authors' published\n",
   "sampler. If this fails, nothing downstream is worth reading."),
code("r = subprocess.run(f'python -m pytest {REPO}/tests -q',\n",
     "                   shell=True, text=True, capture_output=True,\n",
     "                   env={**os.environ, 'PYTHONPATH': f'{REPO}/src'})\n",
     "print(r.stdout[-3000:] or r.stderr[-3000:])\n",
     "assert r.returncode == 0, 'tests failed - stop here'\n"),

md("## Stage 1 - CPU experiments\n",
   "\n",
   "No GPU, no assets. About a minute. This is where most of the project's findings\n",
   "come from, because the analytic problem has a known exact solution and error can\n",
   "be *measured* rather than proxied by FID."),
code("from mlrx.pipeline import run_cpu_stage\n",
     "written, summary = run_cpu_stage(OUTDIR, quick=QUICK_CPU)\n",
     "print(json.dumps(summary, indent=2))\n"),

code("import pandas as pd\n",
     "ab = pd.read_csv(f'{OUTDIR}/results/reuse_ablation_order.csv')\n",
     "print('HEADLINE - fitted local order by level count and reuse mode\\n')\n",
     "for prob, g in ab.groupby('problem'):\n",
     "    print(prob)\n",
     "    print(g.pivot_table(index='n_levels', columns='reuse_mode',\n",
     "                        values='fitted_local_order')\n",
     "           .round(2).to_string(), '\\n')\n"),

md("## Stage 2 - throughput probe\n",
   "\n",
   "One small run, timed, to project the real cost of the sweep on *this* hardware\n",
   "before committing hours to it. If the projection exceeds the session limit,\n",
   "lower `N_IMAGES` or trim `NFE_GRID` and re-run this cell."),
code("from mlrx.runner import GPUContext, Config, run_config\n",
     "from mlrx.experiments import sweeps\n",
     "\n",
     "CTX = dict(network_pkl=f'{ASSETS}/edm-cifar10-32x32-cond-vp.pkl',\n",
     "           detector_pkl=f'{ASSETS}/inception-2015-12-05.pkl',\n",
     "           ref_npz=f'{ASSETS}/cifar10-32x32.npz',\n",
     "           edm_root=EDM, batch_size=BATCH)\n",
     "\n",
     "if RUN_GPU and torch.cuda.is_available():\n",
     "    ctx = GPUContext(device='cuda:0', **CTX)\n",
     "    probe = Config(method='euler', num_steps=10, n_images=1024, tag='probe')\n",
     "    t0 = time.time(); m = run_config(probe, ctx); dt = time.time() - t0\n",
     "    rate = probe.n_images * probe.expected_nfe / dt\n",
     "    print(f'probe: FID {m[\"fid\"]:.2f} on {probe.n_images} imgs in {dt:.0f}s')\n",
     "    print(f'measured throughput: {rate:,.0f} image-NFE/s')\n",
     "\n",
     "    cfgs = sweeps.build_all(n_images=N_IMAGES, nfe_grid=NFE_GRID,\n",
     "                            include_reuse=INCLUDE_REUSE)\n",
     "    est = sweeps.estimate_cost(cfgs, throughput_img_nfe_per_s=rate,\n",
     "                               n_gpus=max(1, torch.cuda.device_count()))\n",
     "    print(f\"\\n{est['n_configs']} configs, {est['image_nfe']/1e6:.1f}M image-NFE\")\n",
     "    print(f\"projected: {est['gpu_hours']:.1f} GPU-h, \"\n",
     "          f\"{est['wall_hours']:.1f} h wall\")\n",
     "    if est['wall_hours'] > 10.5:\n",
     "        print('\\n*** exceeds a comfortable session budget. Either lower N_IMAGES,\\n'\n",
     "              '    trim NFE_GRID, or just run this notebook twice - the sweep\\n'\n",
     "              '    resumes from results/fid_results.csv. ***')\n"),

md("## Stage 3 - the FID sweep\n",
   "\n",
   "Resumable. Every completed configuration is appended to `results/fid_results.csv`\n",
   "immediately and skipped on a later run."),
code("if RUN_GPU and torch.cuda.is_available():\n",
     "    from mlrx.pipeline import run_gpu_stage\n",
     "    figs, df = run_gpu_stage(\n",
     "        OUTDIR, CTX, n_images=N_IMAGES, nfe_grid=NFE_GRID,\n",
     "        n_gpus=max(1, torch.cuda.device_count()),\n",
     "        include_reuse=INCLUDE_REUSE, do_rho_search=DO_RHO_SEARCH)\n",
     "    print(f'\\n{len(df)} configurations recorded')\n",
     "else:\n",
     "    print('GPU stage skipped')\n"),

md("## Results"),
code("import pandas as pd\n",
     "fp = f'{OUTDIR}/results/fid_results.csv'\n",
     "if os.path.exists(fp):\n",
     "    df = pd.read_csv(fp)\n",
     "    gate = df[(df.nfe == 10) & (df.tag.isin(['panel','validity','seedblock']))]\n",
     "    if len(gate):\n",
     "        print('Validation gate, NFE = 10:\\n')\n",
     "        print(gate.groupby('method')['fid'].agg(['mean','std','count'])\n",
     "                  .round(3).to_string())\n",
     "        print('\\nPaper (50k images): Euler 15.88 | Heun 14.46 | RX-Euler 4.35 | RX+EDM 4.26')\n",
     "        print('Ours use 10k images, so they read high - FID is biased upward at\\n'\n",
     "              'smaller sample counts. Compare our methods against each other,\\n'\n",
     "              'not against the published absolute values.')\n"),

code("print('figures:')\n",
     "for f in sorted(glob.glob(f'{OUTDIR}/figures/*.pdf')):\n",
     "    print(f'  {os.path.basename(f):<48} {os.path.getsize(f)/1024:6.1f} KB')\n",
     "print('\\ntables:')\n",
     "for f in sorted(glob.glob(f'{OUTDIR}/results/*.csv')):\n",
     "    print(f'  {os.path.basename(f):<48} {sum(1 for _ in open(f))-1:6d} rows')\n"),

md("## Package the outputs"),
code("import shutil\n",
     "shutil.make_archive('/kaggle/working/mlrx_outputs', 'zip', OUTDIR)\n",
     "print('wrote /kaggle/working/mlrx_outputs.zip '\n",
     "      f'({os.path.getsize(\"/kaggle/working/mlrx_outputs.zip\")/2**20:.1f} MB)')\n"),
]
nb(c2, "02_run_pipeline_offline.ipynb")
